### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by TheBiostarfly** [AdamGuidarini/MediTrak#96]
I installed version 0.12.3 and I don't receive any notifications anymore. It worked before! 
Thank you!

**Comment by AdamGuidarini** [comment]
Hello! Thank you for letting me know. I have a couple questions to help me narrow down the issue

1. What version of Android are you using?
2. More of a debugging step - if you're using Android 12 or newer, does the app have the notification permission enabled? If earlier, is the notifications toggle in Settings on?
3. Would you be able to provide any details about the medications? 
-- Like the schedule, dosage, and name if you feel comfortable. In case there's a data issue such as a character breaking the SQLite query. 
-- if you do feel comfortable sharing this information, you could send it to me at adam.g.software@gmail.com if you'd prefer
4. Is this a fresh install of the app?
5. What does the schedule look like the medication/s?

**Comment by TheBiostarfly** [comment]
So I just tried to do a little test run and create a test medication to see the I would get an notification. But when I tried to save the test medication the app crashed: 

```
type: crash
osVersion: google/oriole/oriole:14/AP1A.240505.004/2024060500:user/release-keys
package: projects.medicationtracker:22
process: projects.medicationtracker
processUptime: 125 + 234 ms
installer: com.looker.droidify

android.os.BadParcelableException: Parcel android.os.Parcel@c3c94f7: Unmarshalling unknown type code 240 at offset 364
	at android.os.Parcel.readValue(Parcel.java:4915)
	at android.os.Parcel.readValue(Parcel.java:4563)
	at android.os.Parcel.readListInternal(Parcel.java:5565)
	at android.os.Parcel.readArrayListInternal(Parcel.java:5584)
	at android.os.Parcel.readValue(Parcel.java:4816)
	at android.os.Parcel.readValue(Parcel.java:4555)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4653)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4612)
	at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:417)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:403)
	at android.os.BaseBundle.getValue(BaseBundle.java:383)
	at android.os.BaseBundle.getArrayList(BaseBundle.java:1529)
	at android.os.Bundle.getParcelableArrayList(Bundle.java:1090)
	at projects.medicationtracker.Fragments.MedicationScheduleFragment.onCreateView(MedicationScheduleFragment.java:110)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1650)
	at android.app.Activity.performStart(Activity.java:8853)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3982)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:299)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:251)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:91)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2551)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```
here are the logs of the crash I hope those are helpful

**Comment by AdamGuidarini** [comment]
Thank you for the information! I tinkered a bit on my own phone (Pixel 6 with Android 14) and while my daily reminder works I tried a multiple per day and that doesn't seem to work. I'm out of town for the weekend unfortunately, but I should have time to dive deeper into it on Monday

**Comment by Phoenix1025** [comment]
Same here, realme c25y android 11. Notifications not working but it did before i installed the app for almost a week now.

**Comment by Phoenix1025** [comment]
> Okay let me try to answer the questions:
> 
> 1. GrapheneOs with Android 14 but no Google play service
> 2. Permission are enabled since it worked before
> 3. I don't think that's part of the problem
> 4. No I upgraded the app from 0.12.1
> 5. I have one medication I take twice a day. Once at 8:00 and once 19:00
> 
> Thanks for your help!

I think the update introduced the bug.

**Comment by AdamGuidarini** [comment]
> Same here, realme c25y android 11. Notifications not working but it did before i installed the app for almost a week now. It only started not to work after i updated it.

Is it also with a multiple per day medication in your case? My daily reminder comes through which is what the last update fixed, but it seems it broke multiple per day notifications in the process

**Comment by Phoenix1025** [comment]
> > Same here, realme c25y android 11. Notifications not working but it did before i installed the app for almost a week now. It only started not to work after i updated it.
> 
> Is it also with a multiple per day medication in your case? My daily reminder comes through which is what the last update fixed, but it seems it broke multiple per day notifications in the process 

Yes, bro i have 3 daily medications and 1 in custom schedule which is taken every other day.

**Comment by AdamGuidarini** [comment]
I'm working on this issue but I'm having a bit of trouble recreating in testing. I did find that on my own device when I force stopped the app an restarted it, notifications worked normally again. A fresh install also seems to resolve the issue, but is more of a pain but you can export data in the old install and import it in the new install in settings. Let me know if you give either of these methods a try and whether or not they worked for you. I'll continue working on determining the cause of the issue in the meantime

**Comment by TheBiostarfly** [comment]
> I'm working on this issue but I'm having a bit of trouble recreating in testing. I did find that on my own device when I force stopped the app an restarted it, notifications worked normally again. A fresh install also seems to resolve the issue, but is more of a pain but you can export data in the old install and import it in the new install in settings. Let me know if you give either of these methods a try and whether or not they worked for you. I'll continue working on determining the cause of the issue in the meantime


So I reinstalled the app as you recommended. The reinstall did fix the bug with the app crashing when trying to create an new medication schedule or opening the 'My Meds' section. I did not resolve the problem with the missing notifications unfortunately.

**Comment by AdamGuidarini** [comment]
Just released version [0.12.4](https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.12.4) that seems to have solved this issue. At least in my own testing. I'm not sure if the error I found was the same one you encountered though, so I'll leave this issue open for the time being

**Comment by TheBiostarfly** [comment]
Thanks a lot! Gonna test the update as soon as it comes through!

**Comment by TheBiostarfly** [comment]
It does work! Prefect. Thank you very much for the fix!

**Comment by AdamGuidarini** [comment]
You're welcome! I'm glad it's working for you again!
